### ISSUE TITLE
Can't run recipe because fails on postfixadmin/recipes/apache.rb

### ISSUE THREAD

**Issue by maurodx** [zuazo/postfixadmin-cookbook#9]
Chef complains about 

    27>>   return if node['apache']['listen_ports'].include?(port)
    
    ERROR: undefined method `include?' for nil:NilClass

I'm running the recipe included by postfix-dovecot cookbook and postfix-dovecot is included in another custom cookbook.

**Comment by zuazo** [comment]
OK, thanks for the report @maurodx. I will look at it over the weekend.

**Comment by zuazo** [comment]
Fixed in master: 8c20c75acc772b4a2dd18f47806db1e12da51472, 9d6bebb38be2d7ea00af4826bef2fecd8d0ea0e8

**Comment by zuazo** [comment]
Fix released in [`3.0.0`](https://github.com/zuazo/postfixadmin-cookbook/releases/tag/3.0.0).
